import { useState, type FormEvent } from 'react';
import { useServerFn } from '@tanstack/react-start';
import { ArrowRight, ArrowDown, Check, Brain, HeartPulse, Apple, Users, ShieldCheck, Armchair, Video, Building2, MessagesSquare, CalendarDays, Mail, Plus, CheckCircle2, Sparkles, Menu, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { categories, formats, faqs, contact, whatsappUrl } from '@/lib/wellness-config';
import { enquirySchema, type Enquiry } from '@/lib/wellness-schema';
import { submitEnquiry } from '@/lib/wellness.functions';
import hero from '@/assets/wellness-session.jpg';
import logo from '@/assets/ezee-logo.png.asset.json';

function WhatsAppIcon({ className }: { className?: string }) {
  return <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d="M20.5 11.6a8.5 8.5 0 0 1-12.6 7.5L3 20.5l1.4-4.8a8.5 8.5 0 1 1 16.1-4.1Z"/><path d="M8 7.3c-.7 0-1.2.8-1.2 1.6 0 2.7 4.3 6.8 7 6.8.9 0 1.8-.8 1.8-1.5l-2.4-1.3-.8 1c-1.7-.7-2.9-1.9-3.6-3.5l.9-.8L8.6 7.3H8Z"/></svg>;
}
const icons = { brain: Brain, heart: HeartPulse, apple: Apple, people: Users, shield: ShieldCheck, desk: Armchair };
const formatIcons = { video: Video, building: Building2, messages: MessagesSquare, calendar: CalendarDays };
const initial: Enquiry = { fullName: '', email: '', company: '', phone: '', topic: '', attendees: '', format: '', city: '', timing: '', notes: '', consent: false, website: '', source: {} };

export function WellnessPage() {
  const [expanded, setExpanded] = useState<string | null>(null);
  const [mobileMenu, setMobileMenu] = useState(false);
  const [form, setForm] = useState<Enquiry>(initial);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [busy, setBusy] = useState(false);
  const [saved, setSaved] = useState(false);
  const send = useServerFn(submitEnquiry);
  function selectTopic(topic: string) {
    setForm(previous => ({ ...previous, topic }));
    setSaved(false);
    document.getElementById('request-session')?.scrollIntoView({ behavior: 'smooth' });
  }
  function update(key: keyof Enquiry, value: string | boolean) { setForm(previous => ({ ...previous, [key]: value })); }
  async function submit(event: FormEvent) {
    event.preventDefault();
    const parsed = enquirySchema.safeParse(form);
    if (!parsed.success) {
      const next: Record<string, string> = {};
      parsed.error.issues.forEach(issue => { next[String(issue.path[0])] = issue.message; });
      setErrors(next); return;
    }
    setBusy(true); setErrors({});
    const source: Record<string, string> = { page: '/corporate-wellness' };
    const params = new URLSearchParams(window.location.search);
    ['utm_source', 'utm_medium', 'utm_campaign'].forEach(key => { const value = params.get(key); if (value) source[key] = value.slice(0, 500); });
    try { const result = await send({ data: { ...parsed.data, source } }); if (result.saved) setSaved(true); }
    catch { setErrors({ submission: 'Your request could not be saved. Please try again or contact us on WhatsApp.' }); }
    finally { setBusy(false); }
  }
  function field(name: 'fullName' | 'email' | 'company' | 'phone' | 'city' | 'timing', label: string, placeholder: string, required = false, type = 'text') {
    return <div><label className="field-label" htmlFor={name}>{label}{required && <span className="text-primary"> *</span>}</label><input id={name} name={name} type={type} value={form[name]} onChange={e => update(name, e.target.value)} placeholder={placeholder} maxLength={name === 'email' ? 255 : 150} className="field-input" autoComplete={name === 'fullName' ? 'name' : name === 'email' ? 'email' : name === 'phone' ? 'tel' : name === 'company' ? 'organization' : 'off'} aria-required={required} aria-invalid={Boolean(errors[name])} aria-describedby={errors[name] ? `${name}-error` : undefined}/>{errors[name] && <p id={`${name}-error`} className="field-error">{errors[name]}</p>}</div>;
  }
  return <>
    <a href="#main" className="sr-only focus:not-sr-only">Skip to content</a>
    <header className="site-header"><div className="site-wrap flex h-full items-center justify-between gap-5">
      <a href="https://ezeeinsure.com" aria-label="Ezee Insure home"><img className="brand-logo" src={logo.url} alt="Ezee Insure" width="152" height="60"/></a>
      <nav className="desktop-nav flex items-center gap-7" aria-label="Main navigation"><a className="nav-link" href="https://ezeeinsure.com/group-health">Insurance solutions</a><a className="nav-link text-primary" href="#topics">Corporate wellness</a><a className="nav-link" href="#how-it-works">How it works</a><a className="nav-link" href="#faq">FAQs</a></nav>
      <div className="flex items-center gap-2"><Button asChild className="action-cta hidden sm:inline-flex"><a href="#request-session">Request a session <ArrowRight/></a></Button><Button variant="ghost" size="icon" className="lg:hidden" aria-label={mobileMenu ? 'Close navigation' : 'Open navigation'} onClick={() => setMobileMenu(!mobileMenu)}>{mobileMenu ? <X/> : <Menu/>}</Button></div>
    </div>{mobileMenu && <nav className="absolute inset-x-0 z-30 flex flex-col gap-5 border-b border-border bg-background p-6" aria-label="Mobile navigation">{[['Wellness topics','#topics'],['How it works','#how-it-works'],['FAQs','#faq'],['Request a session','#request-session']].map(([text, href]) => <a key={href} className="nav-link" href={href} onClick={() => setMobileMenu(false)}>{text}</a>)}</nav>}</header>
    <main id="main">
      <section className="hero">
        <img className="hero-photo" src={hero} alt="An illustrative corporate wellness discussion in a bright workplace" width="1920" height="1024" fetchPriority="high"/>
        <div className="site-wrap hero-content reveal"><div className="eyebrow flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-primary"/> People first. Wellbeing always.</div>
          <h1>Corporate wellness.<br/>Healthier people.<br/><span className="text-primary">Stronger teams.</span></h1>
          <p className="hero-copy">Bring meaningful health conversations to your workplace. Explore wellness talks and workshops, coordinated by Ezee Insure and shaped around your team.</p>
          <div className="mt-7 flex flex-wrap items-center gap-3"><Button asChild className="action-cta"><a href="#request-session">Request a session <ArrowRight/></a></Button><Button variant="ghost" asChild className="action-cta"><a href="#topics">Explore topics <ArrowDown/></a></Button></div>
          <div className="hero-note mt-6 flex flex-wrap gap-x-5 gap-y-2"><span className="flex items-center gap-1.5"><Check className="h-3.5 w-3.5 text-primary"/> Online & onsite options</span><span className="flex items-center gap-1.5"><Check className="h-3.5 w-3.5 text-primary"/> Tailored to your team</span></div>
        </div>
        <div className="hero-proof"><ShieldCheck className="h-8 w-8"/><div><p className="text-xs font-bold">A little awareness. A lasting difference.</p><p className="mt-1 text-[11px] text-muted-foreground">Practical conversations for everyday wellbeing.</p></div></div>
      </section>
      <section id="how-it-works" className="section-space"><div className="site-wrap"><div className="mb-10 flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">Simple from the start</p><h2 className="section-title">Your team. Your needs. We coordinate.</h2></div><p className="max-w-xs text-sm leading-7 text-muted-foreground">Less coordination for HR.<br/>More meaningful moments for your people.</p></div><div className="grid gap-8 md:grid-cols-3">{[
        ['01','Choose a wellness topic','Explore our six areas of wellbeing or tell us what your team needs.'],['02','Tell us about your team','Share your audience, preferred format and a time that works for you.'],['03','Leave the coordination to us','We discuss an appropriate expert, session details and schedule with you.'],
      ].map(([n,title,text]) => <div className="step" key={n}><span className="step-number">{n}</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></div></section>
      <section id="topics" className="section-space bg-muted"><div className="site-wrap"><div className="text-center"><p className="eyebrow">Wellbeing, from every angle</p><h2 className="section-title">What would your team like to explore?</h2><p className="section-copy mx-auto max-w-xl">Six areas of wellness. Conversations that meet your people where they are.</p></div>
        <div className="mt-10 grid items-start gap-5 md:grid-cols-2 lg:grid-cols-3">{categories.map(category => { const Icon = icons[category.icon]; const open = expanded === category.id; return <article key={category.id} className="topic-card"><Button variant="ghost" className="topic-toggle" aria-expanded={open} aria-controls={`topics-${category.id}`} onClick={() => setExpanded(open ? null : category.id)}><span className={`topic-icon tone-${category.tone}`}><Icon/></span><span className="topic-title">{category.title}</span><span className="topic-description">{category.description}</span><span className="topic-explore">Explore sessions <span>{open ? <X/> : <ArrowRight/>}</span></span></Button><div id={`topics-${category.id}`} className="topic-panel" hidden={!open}><ul>{category.topics.map(topic => <li key={topic}><Button variant="link" className="topic-option" onClick={() => selectTopic(topic)}>{topic}<ArrowRight className="ml-auto"/></Button></li>)}</ul><Button className="mt-4 w-full" onClick={() => selectTopic(category.title)}>Request this topic <ArrowRight/></Button></div><div className="sr-only">{category.topics.join('; ')}</div></article>; })}</div>
        <div className="mt-9 flex flex-wrap items-center justify-center gap-2 text-sm"><span className="text-muted-foreground">Something else on your mind?</span><Button variant="link" onClick={() => selectTopic('Custom topic')}>Request a custom session <ArrowRight/></Button></div><p className="mt-4 text-center text-[11px] text-muted-foreground">Educational sessions for workplace wellbeing. Not individual diagnosis or treatment.</p>
      </div></section>
      <section className="section-space"><div className="site-wrap"><p className="eyebrow">Built around your workplace</p><h2 className="section-title">The right conversation. The right format.</h2><p className="section-copy">Share your preferences. We’ll discuss what’s possible for your team.</p><div className="mt-10 grid gap-y-8 grid-cols-2 md:grid-cols-4">{formats.map(format => { const Icon = formatIcons[format.icon]; return <div className="format-item" key={format.title}><Icon/><h3>{format.title}</h3><p>{format.text}</p></div>; })}</div></div></section>
      <section className="section-space trust-band"><div className="site-wrap grid items-center gap-12 md:grid-cols-2"><div><p className="eyebrow">The Ezee approach</p><h2 className="section-title max-w-md">Thoughtful sessions.<br/>One less thing to manage.</h2><p className="section-copy max-w-md">You know your people. We help turn their wellbeing needs into a practical, coordinated conversation.</p><Button asChild variant="secondary" className="action-cta mt-7"><a href="#request-session">Let’s plan your session <ArrowRight/></a></Button></div><div>{[
        [ShieldCheck,'Matched with an appropriate expert','The session topic guides expert selection, with relevant qualifications for specialised subjects.'],[Users,'Relevant to your people','Your audience and workplace needs help shape the discussion.'],[Sparkles,'Convenient corporate coordination','One point of contact to discuss the topic, format, commercial terms and schedule.'],
      ].map(([Icon,title,text]) => { const ItemIcon = Icon as typeof ShieldCheck; return <div className="trust-point" key={String(title)}><ItemIcon/><div><h3>{String(title)}</h3><p>{String(text)}</p></div></div>; })}</div></div></section>
      <section id="faq" className="section-space"><div className="site-wrap grid gap-10 md:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">A few things to know</p><h2 className="section-title">Good questions.<br/>Clear answers.</h2><p className="section-copy max-w-xs">Planning for your team? Here are the details that matter.</p><Button asChild variant="link" className="mt-5 px-0"><a href={whatsappUrl()} target="_blank" rel="noopener noreferrer">Ask us on WhatsApp <ArrowRight/></a></Button></div><div>{faqs.map(faq => <details className="faq-item" key={faq.question}><summary>{faq.question}<Plus/></summary><p>{faq.answer}</p></details>)}</div></div></section>
      <section id="request-session" className="section-space enquiry-section"><div className="site-wrap grid items-start gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Start a healthier conversation</p><h2 className="section-title max-w-md">Let’s put your team’s wellbeing on the agenda.</h2><p className="section-copy max-w-sm">Tell us a little about your team. We’ll discuss the right topic, expert and format together.</p><div className="mt-8"><a className="contact-line" href={whatsappUrl(form.topic)} target="_blank" rel="noopener noreferrer"><WhatsAppIcon/><span>Chat on WhatsApp<br/><span className="mt-1 block text-xs font-normal text-muted-foreground">{contact.phone}</span></span><ArrowRight className="ml-3"/></a><a className="contact-line" href={`mailto:${contact.email}?subject=${encodeURIComponent('Corporate wellness enquiry')}`}><Mail/><span>Email our team<br/><span className="mt-1 block text-xs font-normal text-muted-foreground">{contact.email}</span></span><ArrowRight className="ml-3"/></a></div><p className="mt-10 max-w-xs text-xs leading-6 text-muted-foreground">No commitment at this stage. Session details, expert availability and fees are agreed before confirmation.</p></div>
        <div className="enquiry-form">{saved ? <div className="py-12 text-center" role="status"><CheckCircle2 className="mx-auto h-12 w-12 text-primary"/><h3 className="mt-5 text-2xl font-bold">Thank you for reaching out.</h3><p className="section-copy">Your request has been saved. Our team can review it to discuss your session and expert availability.</p><p className="mt-4 text-xs leading-6 text-muted-foreground">For a direct conversation, you can also message our team.</p><Button asChild className="mt-6 action-cta"><a target="_blank" rel="noopener noreferrer" href={whatsappUrl(form.topic)}><WhatsAppIcon/> Continue on WhatsApp</a></Button><Button variant="link" className="mt-4 block mx-auto" onClick={() => { setSaved(false); setForm(initial); }}>Send another enquiry</Button></div> : <form onSubmit={submit} noValidate><h3 className="text-xl font-bold">Request a wellness session</h3><p className="mt-2 text-xs text-muted-foreground">A few details to get the conversation started.</p><div className="mt-7 grid gap-x-5 gap-y-5 sm:grid-cols-2">{field('fullName','Full name','Your full name',true)}{field('email','Work email','you@company.com',true,'email')}{field('company','Company name','Your organisation',true)}{field('phone','Phone / WhatsApp','+92',true,'tel')}
          <div className="sm:col-span-2"><label className="field-label" htmlFor="topic">Preferred wellness topic <span className="text-primary">*</span></label><select className="field-input" id="topic" value={form.topic} onChange={e => update('topic',e.target.value)} aria-required="true" aria-invalid={Boolean(errors['topic'])}><option value="">Select a topic</option>{categories.map(category => <optgroup key={category.id} label={category.title}><option>{category.title}</option>{category.topics.map(topic => <option key={topic}>{topic}</option>)}</optgroup>)}<option>Custom topic</option></select>{errors['topic'] && <p className="field-error">{errors['topic']}</p>}</div>
          <div><label className="field-label" htmlFor="attendees">Approximate attendees <span className="font-normal text-muted-foreground">(optional)</span></label><select id="attendees" className="field-input" value={form.attendees} onChange={e => update('attendees',e.target.value)}><option value="">Select team size</option>{['Under 25','25–50','51–100','100+','Not sure'].map(n => <option key={n}>{n}</option>)}</select></div><div><label className="field-label" htmlFor="format">Session format <span className="font-normal text-muted-foreground">(optional)</span></label><select id="format" className="field-input" value={form.format} onChange={e => update('format',e.target.value)}><option value="">Select a format</option>{['Online','Onsite','Either'].map(n => <option key={n}>{n}</option>)}</select></div>
          {(form.format === 'Onsite' || form.format === 'Either') && field('city','City (optional)','Your workplace city')}{field('timing','Preferred timing (optional)','e.g. Next month, weekday morning')}
          <div className="sm:col-span-2"><label className="field-label" htmlFor="notes">Anything else we should know? <span className="font-normal text-muted-foreground">(optional)</span></label><textarea id="notes" className="field-input min-h-24 resize-y" value={form.notes} onChange={e => update('notes',e.target.value)} maxLength={2000} placeholder="Tell us about your goals or a custom topic. Please don’t include personal medical information."/></div>
        </div><div className="hidden" aria-hidden="true"><label htmlFor="website">Website</label><input id="website" tabIndex={-1} autoComplete="off" value={form.website} onChange={e => update('website',e.target.value)}/></div><label className="mt-5 flex items-start gap-3 text-[11px] leading-5 text-muted-foreground"><input className="mt-1 h-4 w-4 shrink-0 accent-primary" type="checkbox" checked={form.consent} onChange={e => update('consent',e.target.checked)}/> <span>I agree to Ezee Insure contacting me about this request and to the <a className="text-primary underline" href={contact.privacy} target="_blank" rel="noopener noreferrer">Privacy Policy</a>.</span></label>{errors['consent'] && <p className="field-error">{errors['consent']}</p>}{errors['submission'] && <p className="field-error mt-4" role="alert">{errors['submission']}</p>}<Button className="action-cta mt-6 w-full" type="submit" disabled={busy}>{busy ? 'Sending your request…' : 'Request a session'}<ArrowRight/></Button><p className="mt-3 text-center text-[10px] text-muted-foreground">Your details are used to coordinate your enquiry. This is not a confirmed booking.</p></form>}</div>
      </div></section>
    </main>
    <footer className="site-footer"><div className="site-wrap"><div className="flex flex-wrap items-start justify-between gap-8"><div><a href="https://ezeeinsure.com"><img src={logo.url} alt="Ezee Insure" className="footer-logo" width="140" height="50" loading="lazy"/></a><p className="mt-3 text-xs text-muted-foreground">Making protection and wellbeing a little more Ezee.</p></div><div className="flex flex-wrap gap-6 text-xs text-muted-foreground"><a href="https://ezeeinsure.com/group-health">Group health insurance</a><a href="https://ezeeinsure.com/about">About Ezee</a><a href={contact.privacy}>Privacy policy</a><a href={`mailto:${contact.email}`}>Contact us</a></div></div><div className="mt-9 flex flex-wrap justify-between gap-3 border-t border-border pt-6 text-[10px] text-muted-foreground"><p>© {new Date().getFullYear()} Ezee Insure. All rights reserved.</p><a href="https://ezeeinsure.com/terms-and-conditions">Terms & conditions</a></div></div></footer>
    <div className="mobile-cta"><Button asChild className="w-full"><a href="#request-session">Request a session <ArrowRight/></a></Button></div><Button asChild className="whatsapp-float" size="icon"><a href={whatsappUrl(form.topic)} target="_blank" rel="noopener noreferrer" aria-label="Chat with Ezee Insure on WhatsApp" title="Chat on WhatsApp"><WhatsAppIcon/></a></Button>
  </>;
}